### ISSUE TITLE
Schema.dump(None) Should Follow JSONAPI Spec

### ISSUE THREAD

**Issue by rgant** [marshmallow-code/marshmallow-jsonapi#58]
According to the [JSONAPI Spec](http://jsonapi.org/format/#document-top-level):

> Primary data MUST be either... a single resource object, a single resource identifier object, or null, for requests that target single resources

And when [fetching empty relationships](http://jsonapi.org/format/#fetching-relationships-responses-200) you must return a 200 with a `null` or `[]` for the data key.

In this example we don't properly follow the spec:
```python
>>> from marshmallow_jsonapi import Schema, fields
>>> class PostSchema(Schema):
...     id = fields.Str(dump_only=True)
...     class Meta:
...         type_ = 'posts'
...         strict = True
... 
>>> schema = PostSchema()
>>> schema.dump(None).data
{'data': {'type': 'posts'}}
>>> schema.dump([]).data
{'data': {'type': 'posts'}}
```

Further there is an issue with self links and None or [] objects:
```python
>>> class PostSchema(Schema):
...     id = fields.Str(dump_only=True)
...     class Meta:
...         type_ = 'posts'
...         strict = True
...         self_url_kwargs = {'id': '<id>'}
...         self_url = '/articles/{id}'
... 
>>> schema = PostSchema()
>>> schema.dump(None).data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./marshmallow/schema.py", line 515, in dump
    original_data=obj)
  File "./marshmallow/schema.py", line 830, in _invoke_dump_processors
    data=data, many=many, original_data=original_data)
  File "./marshmallow/schema.py", line 930, in _invoke_processors
    data = utils.if_none(processor(data, many), data)
  File "./marshmallow_jsonapi/schema.py", line 113, in format_json_api_response
    ret = self.format_items(data, many)
  File "./marshmallow_jsonapi/schema.py", line 276, in format_items
    return self.format_item(data)
  File "./marshmallow_jsonapi/schema.py", line 263, in format_item
    links = self.get_resource_links(item)
  File "./marshmallow_jsonapi/schema.py", line 294, in get_resource_links
    kwargs = resolve_params(item, self.opts.self_url_kwargs or {})
  File "./marshmallow_jsonapi/utils.py", line 33, in resolve_params
    'attribute of {obj!r}'.format(attr_name=attr_name, obj=obj)
AttributeError: 'id' is not a valid attribute of {}
```
(Same is true for `[]`)

I'm working on a fork and a fix for this currently.

**Comment by rgant** [comment]
I've completed my changes and submitted a pull request. One day maybe github will allow me to use an existing Issue as a pull request so there aren't duplicates.
